# Imagen base de Python
FROM python:3.12-slim

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el archivo Python al contenedor
COPY hola_mundo_web.py .

# Exponemos el puerto donde corre el servidor
EXPOSE 8080

# Comando que se ejecuta al iniciar el contenedor
CMD ["python", "hola_mundo_web.py"]
